# NOTE: This pipeline depends on the following variable groups: 

# Name of variable group          Keys inside variable group
# ----------------------          --------------------------
# redgate_global_vars             FLYWAY_LICENSE_KEY, AGENT_POOL
# redgate_pipeline_vars           BASELINE_VERSION, FIRST_UNDO_SCRIPT
# redgate_build_credentials       userName, password, target_database_JDBC, databaseName
# redgate_test_credentials        userName, password, target_database_JDBC, databaseName, check_JDBC, check_userName, check_password

# Every target database will need its own variable group, which is referenced in a YML deployment script

name: Bolt-self-hosted-pipeline-templatized
 
trigger:
  branches:
    include:
      - release
  paths:
    include:
      - migrations/*
      
resources:
  repositories:
    - repository: templates
      type: git
      name: templates

variables:
- template: vars.yml@templates

stages:

- template: deploy.yml@templates                        # templates/deploy.yml if kept in same repository
  parameters:
    stage: Test
    displayName: Deploy Test
    generateDriftAndChangeReport: true                  # optional flag, defaults to false           
    staticCodeAnalysis: true                            # optional flag, defaults to false            
    targetCredentials: bolt_test_credentials
    pipelineParameters: bolt_pipeline_vars

- template: deploy.yml@templates                        # templates/deploy.yml if kept in same repository
  parameters:
    stage: Production
    dependsOn: Test
    pauseForCodeReview: true                            # optional flag, defaults to false
    failReleaseIfDriftDetected: true                    # optional flag, defaults to false
    generateDriftAndChangeReport: true                  # optional flag, defaults to false           
    staticCodeAnalysis: true                            # optional flag, defaults to false 
    displayName: Deploy to Production
    targetCredentials: bolt_prod_credentials
    pipelineParameters: bolt_pipeline_vars